; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:rpipico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
framework = arduino
board_build.core = earlephilhower
board_build.arduino.earlephilhower.usb_manufacturer = Touchstone Technologies
board_build.arduino.earlephilhower.usb_product = Touchpoint Mouse
board_build.arduino.earlephilhower.usb_vid = 0xABCD
board_build.arduino.earlephilhower.usb_pid = 0x1337
monitor_speed = 115200
build_flags =
	-DCORE_DEBUG_LEVEL=0
	-DUSE_TINYUSB
	-DPIO_FRAMEWORK_ARDUINO_ENABLE_FREERTOS
lib_deps =
	adafruit/Adafruit TinyUSB Library@^3.7.4
	adafruit/Adafruit Unified Sensor@^1.1.15
	adafruit/Adafruit NeoPixel@^1.15.4
	adafruit/Adafruit BNO08x@^1.2.5
	adafruit/Adafruit DRV2605 Library@^1.2.4
	adafruit/Adafruit BusIO@^1.17.2
	hideakitai/ArduinoEigen@^0.3.2
	SPI
	Servo
lib_ldf_mode = deep
